### ISSUE TITLE
Två kommentarer postas

### ISSUE THREAD

**Issue by dasovm** [ericwenn/local-feud#47]
När jag testar skicka kommentarer på en post så skickas två åt gången, och jag är för trött för att förstå varför. Why?!

**Comment by dasovm** [comment]
Verkar bara vara på post id 18 (med max tecken)? What??

**Comment by ericwenn** [comment]
Behandlas inte olika på servern, tror det ligger i klienten. Men får kolla
på det :)
Den 4 maj 2016 5:11 em skrev "David Söderberg" notifications@github.com:

Verkar bara vara på post id 18 (med max tecken)? What??

**Comment by dasovm** [comment]
@ericwenn 
Du har troligtvis helt rätt. Kan du testa att kommentera post 18 och se om det postas två likadana kommentarer?

**Comment by dasovm** [comment]
Har ej uppstått fler gånger, close:ar issuet
