### ISSUE TITLE
Logga ut -> Logga in skapar två MainActivity

### ISSUE THREAD

**Issue by dasovm** [ericwenn/local-feud#57]
### När användaren loggar ut och sedan loggar in så skapas två MainActivity

Detta gör att när användaren sedan trycker på bakåt knappen och förväntas att appen stängs, så öppnas en ny MainActivity.

Problemet uppstår av att [denna change-listener](https://github.com/ericwenn/local-feud/blob/development/project/app/src/main/java/com/chalmers/tda367/localfeud/authentication/AuthenticationFlowActivity.java#L33) körs två gånger när användaren loggar in efter att ha loggat ut. Bägge gångerna är (currentAccessToken != null) och därför skapas två Intent som skickar användaren till MainActivity. Det senast skapade intentet aktiveras så fort första MainActivity kör onDestroy()

**Comment by ericwenn** [comment]
Good find. Har funderat på om man ska göra det till ett singleton liknande objekt istället.

PS. Vilken fantastisk issue-text.

**Comment by dasovm** [comment]
Stort tack @ericwenn , la ner mycket tid på denna. Bjöd till och med på en snygg label!
