### ISSUE TITLE
Refactoring på controls-paketet

### ISSUE THREAD

**Issue by ericwenn** [ericwenn/local-feud#66]
Vi delar upp paketet `control` i `activity`, `adapter`, `fragment`.

```
-- control
   /-- activity
   /-- adapter
   /-- fragment
```

**Comment by ericwenn** [comment]
Byta namn på aktiviteter så de följer samma mönster
Exempelvis: 
`PostClickedActivity` -> `PostActivity`
"Vad nu klassen som hanterar postlistan heter" -> `PostListActivity`

**Comment by ericwenn** [comment]
Uppdaterad struktur efter Christers respons:

```
-- control
   / -- chat
   / -- post
   / -- me
   / -- authentication
   / -- permission
```

**Comment by alfredgunnar** [comment]
@dasovm har löst!
